name: Swap Adapters pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
    lint-compile-test:
     runs-on: ubuntu-latest
     strategy:
      matrix:
        node-version: [14.x]
    
     env:
      MAIN_RPC_URL: ${{ secrets.MAIN_RPC_URL}}
      MATIC_RPC_URL: ${{ secrets.MATIC_RPC_URL}}
      MNEMONIC: ${{ secrets.MNEMONIC}}

     steps:
      - name: Checkout Use Node.js ${{ matrix.node-version}}
        uses: actions/checkout@v2
        with:
         token: ${{secrets.PAT}}
         submodules: recursive
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: npm-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: npm-v2-
      - name: Install
        run: |
          yarn install --frozen-lockfile
      - name: Lint
        run: |
          yarn lint
      - name: Compile
        run: |
          yarn compile
      - name: Test
        run: |
          yarn test:mainnet:fork
